# -*- coding": "utf-8 -*-
"""
Created on Tue Dec 10 10:11:24 2013

@author": "thomas
"""
# Reference :
# http://www.lilypond.org/doc/v2.16/Documentation/notation/percussion-notes


PERCUSSION_NOTES = {"acousticbassdrum": "bda",
                    "bassdrum": "bd",
                    "snare": "sn",
                    "electricsnare": "sne",
                    "acousticsnare": "sna",
                    "lowfloortom": "tomfl",
                    "highfloortom": "tomfh",
                    "lowtom": "toml",
                    "hightom": "tomh",
                    "lowmidtom": "tomml",
                    "himidtom": "tommh",
                    "closedhihat": "hhc",
                    "hihat": "hh",
                    "pedalhihat": "hhp",
                    "openhihat": "hho",
                    "halfopenhihat": "hhho",
                    "crashcymbala": "cymca",
                    "crashcymbal": "cymc",
                    "ridecymbala": "cymra",
                    "ridecymbal": "cymr",
                    "chinesecymbal": "cymch",
                    "splashcymbal": "cyms",
                    "crashcymbalb": "cymcb",
                    "ridecymbalb": "cymrb",
                    "ridebell": "rb",
                    "cowbell": "cb",
                    "mutehibongo": "bohm",
                    "hibongo": "boh",
                    "openhibongo": "boho",
                    "mutelobongo": "bolm",
                    "lobongo": "bol",
                    "openlobongo": "bolo",
                    "mutehiconga": "cghm",
                    "muteloconga": "cglm",
                    "openhiconga": "cgho",
                    "hiconga": "cgh",
                    "openloconga": "cglo",
                    "loconga": "cgl",
                    "hitimbale": "timh",
                    "lotimbale": "timl",
                    "hiagogo": "agh",
                    "loagogo": "agl",
                    "hisidestick": "ssh",
                    "sidestick": "ss",
                    "losidestick": "ssl",
                    "shortguiro": "guis",
                    "longguiro": "guil",
                    "guiro": "gui",
                    "cabasa": "cab",
                    "maracas": "mar",
                    "shortwhistle": "whs",
                    "longwhistle": "whl",
                    "handclap": "hc",
                    "tambourine": "tamb",
                    "vibraslap": "vibs",
                    "tamtam": "tt",
                    "claves": "cl",
                    "hiwoodblock": "wbh",
                    "lowoodblock": "wbl",
                    "mutecuica": "cuim",
                    "opencuica": "cuio",
                    "mutetriangle": "trim",
                    "triangle": "tri",
                    "opentriangle": "trio",
                    "oneup": "ua",
                    "twoup": "ub",
                    "threeup": "uc",
                    "fourup": "ud",
                    "fiveup": "ue",
                    "onedown": "da",
                    "twodown": "db",
                    "threedown": "dc",
                    "fourdown": "dd",
                    "fivedown": "de"
                    }
